"""Canonical Admission bindings owned by eidolon_sdk."""

from eidolon_sdk.device_foundation.v1 import (  # noqa: F401
    AckClaimGrant,
    AckClaimGrantResult,
    AdmissionCredential,
    AdmissionCredentialError,
    AdmissionEventSource,
    AdmissionEventType,
    AdmissionListCursor,
    ApprovalDecision,
    BusinessOwnerId,
    CancelEnrollment,
    CancelEnrollmentResult,
    ClaimActivatedEvent,
    ClaimEventCursor,
    ClaimEventPage,
    ClaimEventStreamItem,
    ClaimGrant,
    ClaimGrantAAD,
    ClaimGrantWireEnvelope,
    ClaimPage,
    ClaimQuery,
    ClaimRecord,
    ClaimRevokedEvent,
    ClaimState,
    CollectClaimGrant,
    CollectClaimGrantResult,
    CommandResult,
    ControllerActorRef,
    CreateEnrollment,
    CreateEnrollmentResult,
    DecideEnrollment,
    DecideEnrollmentResult,
    DeviceProblem,
    DeviceRef,
    EnrollmentProposal,
    EnrollmentProposalPage,
    EnrollmentProposalQuery,
    EnrollmentProposalState,
    EnrollmentRecoveryProjection,
    GrantDeliveryRecord,
    ManifestRef,
    OwnerDomainId,
    RevokeClaim,
    RevokeClaimResult,
    derive_device_instance_id,
    issue_admission_credential,
    read_admission_credential,
)

__all__ = [name for name in globals() if not name.startswith("_")]
