"""Small persistence ports exposed to application use cases."""

from __future__ import annotations

from typing import Protocol

from hub.domain.devices.entities import DeviceDirectoryEntry, ManagedDevice


class DeviceRepository(Protocol):
    async def get(self, device_id: str) -> ManagedDevice | None: ...
    async def get_by_enrollment_id(self, enrollment_id: str) -> ManagedDevice | None: ...
    async def upsert(self, device: ManagedDevice) -> ManagedDevice: ...
    async def list_all(self) -> tuple[ManagedDevice, ...]: ...


class DeviceDirectoryRepository(Protocol):
    async def get(self, *, owner_scope: str, device_id: str) -> DeviceDirectoryEntry | None: ...
    async def upsert(self, entry: DeviceDirectoryEntry) -> DeviceDirectoryEntry: ...
    async def list(self, *, owner_scope: str) -> tuple[DeviceDirectoryEntry, ...]: ...


class DeviceDirectoryProjector(Protocol):
    async def execute(self, device_id: str) -> DeviceDirectoryEntry: ...
