services:
  livekit:
    image: livekit/livekit-server:v1.11.0
    container_name: livekit
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    command:
      - "--config"
      - "/etc/livekit.yaml"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
      - /etc/nginx/ssl/yangtzeailab.com/fullchain.pem:/etc/certs/fullchain.pem:ro
      - /etc/nginx/ssl/yangtzeailab.com/privkey.pem:/etc/certs/privkey.pem:ro
